### ISSUE TITLE
White flash and load speed improvement

### ISSUE THREAD

**Issue by atomGit** [rishabhmw/sauron#12] opened 2019-04-16 14:16 UTC
i think i understand why there's a significant delay (depending on page load time) in applying the CSS as opposed to similar extensions, and this one does seem to produce a better result, however i wonder if the 'white flash' syndrome could be reduced by applying a very minimal temp style before page load completes, something along the lines of...

```
html {
    background: #000 !important;
    color: #fff !important;
}
```

**Comment by rishabhmw** [comment] 2019-04-17 05:16
This is already done via the `baseStyle function` in `content.js`. I haven't noticed white flash syndrome in chrome on my machine,  however, it does come up on firefox from time to time. Which browser are you using? One better way to solve this problem is to modify browser base css, but whether it is in scope of an extension or not that we'll have to look into.

**Comment by atomGit** [comment] 2019-04-17 12:41
i'm using Firefox 66

i noticed different effects with different 'dark web' extensions - with [Midnight Lizard](https://addons.mozilla.org/en-US/firefox/addon/midnight-lizard-quantum/) for example the 'white flash' is entirely eliminated nearly all of the time when using it's 'simplified' mode - whatever they're doing, they seem to be injecting the CSS very early

my idea regarding the base style was to get something injected as soon as possible, then change it again slightly later in the page load process, so the !important stuff in that case would be loaded, then changed

regarding the browser CSS, i haven't hardly looked at the FF WebExt API, but it seems very limited, which is actually what sent me seeking a replacement for [Dark Background and Light Text](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/) - he is using `content-security-policy` (CSP) in the code to modify an http header apparently and that is a problem with FF because if 2+ extensions modify a header on the same page, only one will succeed

**Comment by rishabhmw** [comment] 2019-04-17 20:07
> Firefox 66

Why am I not surprised smh. So it turns out that Firefox loads a frame before it loads a webpage. This frame is the infamous white flash. Here's how to fix it:

1. Menu > Help > Troubleshooting Information
2. Profile Folder > Open Folder
3. Create a new folder named `chrome`
4. Open Notepad and copy the following in it
`#browser vbox#appcontent tabbrowser,
#content,
#tabbrowser-tabpanels,
browser[type=content-primary],
browser[type=content] > html {
  background: #000 !important
}`
5. In Notepad File > Save As > File name : `userChrome.css` Save as type : All Files
6. Save it and copy and paste the file inside the `chrome` folder from step 3.
7. Restart Firefox.

I'll add a way to fix this in Sauron when I get time. Let me know if this fixed your problem so that I can close this issue.

**Comment by atomGit** [comment] 2019-04-17 21:39
i actually already use Shadowfox - i thought it might have contributed to the problem, so i disabled all custom CSS, but that wasn't the issue

i also added the code you pasted to userChrome to make sure it was being loaded and that didn't help either - thanks for finding that bit of code by the way - i had been trying to locate that in Shadfox

i'm going to keep testing Midnight Lizard for now, so you can close this issue if you wish

**Comment by rishabhmw** [comment] 2019-04-18 03:04
It certainly did eliminate the white flash from my machine, weird that it doesn't work for you. Two question - are you using a dark theme along with Sauron? and which other extensions are enabled (try disabling any "theming based" extensions).
Thanks for checking out Sauron.

**Comment by atomGit** [comment] 2019-04-18 18:11
> are you using a dark theme along with Sauron?

Shadowfox, but i eliminated the possibility that it was causing a problem

no other theme extensions

maybe it's hardware specific, who knows

**Comment by rishabhmw** [comment] 2019-04-18 18:58
Alright, Make sure there isn't any other file in the chrome folder and the userChrome.css contains only the styles mentioned above and is a Cascading StyleSheet file and not a txt.
I have added a direct syle to HTML which will be applied before any page content is loaded. After several attempts I can't reproduce the white flash anymore. This will probably solve the problem:
1. Download and extract this repository and disable Sauron in firefox settings.
2. Delete the screenshots folder and then zip all the files in sauron-master (the zip shouldn't contain any folders). Go to Firefox and type `about:debuging` in address bar > Check enable add-on debugging then Load temporary add-on and then select the zip file you created.

**Comment by rishabhmw** [comment] 2019-04-18 19:41
I was able to reproduce the problem when I intentionally kept my PC busy. If the above doesn't solve the problem or doesn't reduce the white flash to your acceptable time, a simpler addon is a better choice for you until Sauron receives a thorough speed optimization. Maybe If it gets rid of `mutation-summary` and uses its own `mutation observer` but it isn't planned in the near future.

**Comment by rishabhmw** [comment] 2019-07-24 12:18
Sauron (Since v1.3) attaches a "Flash Shield" ASAP which is only removed after all mutations are done.
I wasn't able to reproduce the white flash problem anymore on both Firefox and Chrome. Also Sauron now avoids manipulating a single element multiple times and the process is more streamlined giving it a considerable speed boost.

**Closed** 2019-07-24 12:19 UTC
Labels: Implemented, enhancement, fixed
